import 'package:flutter/material.dart';
import '../../../database/database_helper.dart';
import '../../../widgets/bus_card.dart';
import '../../expenses/add_expense_screen.dart';
import '../../fuel/add_fuel_screen.dart';
import '../../orders/add_order_screen.dart';
import '../../trips/add_extra_trip_screen.dart';
import '../../finance/notes_screen.dart';
import '../../bus/pro_tools_screen.dart';

class TodayProSection extends StatefulWidget { const TodayProSection({super.key}); @override State<TodayProSection> createState()=>_TodayProSectionState(); }
class _TodayProSectionState extends State<TodayProSection>{ final db=DatabaseHelper.instance; List<Map<String,Object?>> obligations=[],plans=[]; @override void initState(){super.initState();load();} Future<void> load()async{final o=await db.getMoneyObligations(),p=await db.getServicePlans();if(mounted)setState((){obligations=o;plans=p;});} double get due=>obligations.fold(0,(a,r)=>a+((r['remaining'] as num?)?.toDouble()??0)); Future<void> quick()async{await showModalBottomSheet(context:context,showDragHandle:true,builder:(c)=>SafeArea(child:Wrap(children:[const ListTile(title:Text('Быстро добавить',style:TextStyle(fontWeight:FontWeight.bold))),_item(c,Icons.local_taxi,'Заказ',const AddOrderScreen()),_item(c,Icons.add_road,'Доп. рейс',const AddExtraTripScreen()),_item(c,Icons.local_gas_station,'Заправку',const AddFuelScreen()),_item(c,Icons.receipt_long,'Расход',const AddExpenseScreen()),_item(c,Icons.note_alt_outlined,'Заметку',const NotesScreen()),_item(c,Icons.dashboard_customize_outlined,'Центр 5.0',const ProToolsScreen())])));await load();} Widget _item(BuildContext sheet,IconData icon,String title,Widget page)=>ListTile(leading:Icon(icon),title:Text(title),onTap:(){Navigator.pop(sheet);Navigator.of(context).push(MaterialPageRoute(builder:(_)=>page));}); @override Widget build(BuildContext context){return Column(children:[SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:quick,icon:const Icon(Icons.add_circle_outline),label:const Text('Быстрые действия'))),if(obligations.isNotEmpty||plans.isNotEmpty)...[const SizedBox(height:12),BusCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.priority_high),SizedBox(width:8),Text('Требует внимания',style:TextStyle(fontSize:17,fontWeight:FontWeight.bold))]),if(due>0)Padding(padding:const EdgeInsets.only(top:8),child:Text('Возвраты / восстановление счетов: ${due.toStringAsFixed(0)} ₽')),if(plans.isNotEmpty)Padding(padding:const EdgeInsets.only(top:6),child:Text('ТО и напоминания: ${plans.length}'))]))]]);}}
